import { GlobalStyles } from '@/common/styles/global'
import QueryProvider from '@/common/lib/react-query'
import { ReduxProvider } from '@/common/lib/redux/provider'
import StyledComponentsRegistry from '@/common/lib/registry'
import type { Metadata } from 'next'

import { Poppins } from 'next/font/google'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppies = Poppins({
  weight: ['400', '500', '600', '700'],
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br">
      <body>
        <ReduxProvider>
          <StyledComponentsRegistry>
            <QueryProvider>
              <GlobalStyles />
              <main className={poppies.className}>{children}</main>
            </QueryProvider>
          </StyledComponentsRegistry>
        </ReduxProvider>
      </body>
    </html>
  )
}
